name = "cyphonvoid/hello_world"
version = "0.0.0"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cyphonvoid/hello_world'"

[repository]
user = "cyphonvoid"
project = "hello_world"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
